# cart005_code.py
"""
Cart 005: Code Module
Creates new code, scaffolds languages, and provides snippet libraries.

Features:
- Generators for Python/JS/HTML/CSS with templates
- Snippet library (logging, CLI, web server, data model)
- Minimal AST-like utilities (tokenizing identifiers)
- Export artifacts and audit logs
- CLI: gen <lang> <name> <prompt> | snippet <type> | bundle
"""

import sys, os, json, re

ROOT = os.path.dirname(os.path.abspath(__file__))
LOGS_DIR = os.path.join(ROOT, "logs")
OUT_DIR = os.path.join(ROOT, "artifacts")
os.makedirs(LOGS_DIR, exist_ok=True)
os.makedirs(OUT_DIR, exist_ok=True)
AUDIT = os.path.join(LOGS_DIR, "code_audit.jsonl")

def audit(entry):
    entry = dict(entry)
    entry["t"] = __import__("time").strftime("%Y-%m-%dT%H:%M:%S", __import__("time").gmtime())
    with open(AUDIT, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry) + "\n")

# ---------- Generators ----------
def gen_python(name: str, prompt: str) -> str:
    return f'''"""
{prompt}
"""

import argparse, json, sys

def run():
    parser = argparse.ArgumentParser("{name}")
    parser.add_argument("--input", help="Input file", default=None)
    args = parser.parse_args()
    if args.input:
        with open(args.input,"r") as f:
            data = f.read()
        print(json.dumps({{"len": len(data)}}, indent=2))
    else:
        print("Hello from {name} :: {prompt}")

if __name__ == "__main__":
    run()
'''

def gen_js(name: str, prompt: str) -> str:
    return f'''// {name}: {prompt}
export function main(input) {{
  if (!input) {{
    console.log("Hello from {name} :: {prompt}");
    return;
  }}
  const len = (typeof input === 'string') ? input.length : JSON.stringify(input).length;
  console.log({{ len }});
}}
'''

def gen_html(name: str, prompt: str) -> str:
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"><title>{name}</title>
  <style>body{{font-family:system-ui;background:#0b0f14;color:#e8f0ff}}</style>
</head>
<body>
  <h1>{name}</h1>
  <p>{prompt}</p>
</body>
</html>
'''

def gen_css(name: str, prompt: str) -> str:
    return f'''/* {name}: {prompt} */
:root {{
  --bg:#0b0f14; --fg:#e8f0ff; --accent:#67d1ff;
}}
body {{ background: var(--bg); color: var(--fg); font-family: system-ui; }}
h1 {{ color: var(--accent); }}
'''

LANG_MAP = {
    "python": gen_python,
    "js": gen_js,
    "html": gen_html,
    "css": gen_css
}

# ---------- Snippets ----------
SNIPPETS = {
    "logging": '''import logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("app")
logger.info("Initialized")''',
    "cli": '''import argparse
parser = argparse.ArgumentParser("tool")
parser.add_argument("--flag", action="store_true")
args = parser.parse_args()
print("Flag:", args.flag)''',
    "web_server": '''from http.server import BaseHTTPRequestHandler, HTTPServer
class H(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200); self.end_headers()
        self.wfile.write(b"Hello")
HTTPServer(("0.0.0.0", 8080), H).serve_forever()''',
    "data_model": '''class Item:
    def __init__(self, id, name): self.id=id; self.name=name
    def to_dict(self): return {"id": self.id, "name": self.name}'''
}

# ---------- AST-like utilities ----------
def tokenize_identifiers(code: str) -> list:
    return re.findall(r"[A-Za-z_][A-Za-z0-9_]*", code)

# ---------- Export ----------
def save_text(name: str, text: str) -> str:
    path = os.path.join(OUT_DIR, f"{name}.txt")
    with open(path, "w", encoding="utf-8") as f: f.write(text)
    return path

def bundle_example():
    py = gen_python("example_py", "Example Python generator")
    js = gen_js("example_js", "Example JS generator")
    html = gen_html("example_html", "Example HTML generator")
    ids = tokenize_identifiers(py + js + html)
    return {"ids_count": len(ids), "sample_ids": ids[:20]}

def main():
    args = sys.argv[1:]
    if not args:
        audit({"action": "bundle"})
        b = bundle_example()
        path = save_text("code_bundle", json.dumps(b, indent=2))
        print(json.dumps(b, indent=2)); print(f"Saved: {path}"); return
    cmd = args[0]
    audit({"action": "cli", "cmd": cmd})
    if cmd == "gen":
        lang = args[1]; name = args[2]; prompt = " ".join(args[3:]) if len(args) > 3 else "Generated by Code Module"
        fn = LANG_MAP.get(lang)
        if not fn:
            print("Unknown lang. Use: python|js|html|css"); return
        text = fn(name, prompt); path = save_text(f"{name}.{lang}", text)
        print(json.dumps({"ok": True, "path": path}, indent=2))
    elif cmd == "snippet":
        t = args[1]
        s = SNIPPETS.get(t)
        if not s:
            print("Unknown snippet. Use:", ", ".join(SNIPPETS.keys())); return
        path = save_text(f"snippet_{t}", s)
        print(json.dumps({"ok": True, "path": path}, indent=2))
    elif cmd == "tokens":
        code = " ".join(args[1:]) if len(args) > 1 else "def main(): pass"
        toks = tokenize_identifiers(code)
        print(json.dumps({"count": len(toks), "tokens": toks[:50]}, indent=2))
    else:
        print("Unknown. Try: gen | snippet | tokens | bundle")

if __name__ == "__main__":
    main()